<?php
/**
 * @var $this \Cubex\View\Layout
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <base href="/">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="fragment" content="!">
  <title><?= $this->getData('title', 'Fortifi UI Examples'); ?></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= \Packaged\Dispatch\AssetManager::generateHtmlIncludes(\Packaged\Dispatch\AssetManager::TYPE_CSS); ?>
</head>
<body>
<div id="title-bar">
  <h1>Fortifi UI</h1>
  <ul class="title-bar-nav">
    <?php foreach($this->getData('views') as $uri => $obj) { ?>
      <li><a href="/<?= $uri; ?>"><?= $obj->getDisplayName(); ?></a></li>
    <?php } ?>
  </ul>
</div>

<div id="wrapper">
  <?= $this->content(); ?>
</div>
<?= \Packaged\Dispatch\AssetManager::generateHtmlIncludes(\Packaged\Dispatch\AssetManager::TYPE_JS); ?>
</body>
</html>
